services:
  product-api:
    image: "node:23-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./product-api:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: sh -c "npm config set strict-ssl false && npm ci && npm run start:dev"
  
  order-api:
    image: golang:1.23
    working_dir: /usr/src/app
    volumes:
      - ./order-api:/usr/src/app
    expose:
      - "1323"
    ports:
      - "1323:1323"
    command: go run main.go